version: '3.9'

services:
  todo_app:
    container_name: todo_app
    image: my_todo_app
    build: .
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:postgresql://todo_app_db:5432/todo_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - todo_app_db

  todo_app_db:
    container_name: todo_app_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - todo_app_pgdata:/var/lib/postgresql/data

volumes:
  todo_app_pgdata: {}
